debug: false

output_format:
  Screen: true
  CSV: false
  Excel: false
  All: false
  Default: Screen

timeframes:
  services:
    from_time: "now-30m"
    to_time: "now"
    resolution: "1m"
  databases:
    from_time: "now-7d"
    to_time: "now"
    resolution: "5m"

services:
  - name: "ComercioTransaccionesController"
    id: "SERVICE-FD9343224D905203"
    threshold_ms: 3000
    metrics:
      response_time: "builtin:service.response.time"
      client_time: "builtin:service.response.client"
      request_count: "builtin:service.requestCount.total"
      success_count: "builtin:service.errors.server.successCount"
      failure_count: "builtin:service.errors.server.count"
      failure_rate: "builtin:service.errors.total.rate"
      server_failure_rate: "builtin:service.errors.server.rate"
      server_success_rate: "builtin:service.successes.server.rate"
    calculated_metrics:
      filter_details_response_time: "calc:service.responsetime_trxmediospago_filterdetails"
      filter_details_request_count: "calc:service.requestcount_trxmediospago_filtersales"
      filter_sales_response_time: "calc:service.responsetime_trxmediospago_filtersales"
      filter_sales_request_count: "calc:service.requestcount_trxmediospago_filtersales"

  - name: "AbonosController"
    id: "SERVICE-123E236BA4855F4A"
    threshold_ms: 3000
    metrics:
      response_time: "builtin:service.response.time"
      request_count: "builtin:service.requestCount.total"
      success_count: "builtin:service.errors.server.successCount"
      failure_count: "builtin:service.errors.server.count"

databases:
  - name: "mc_tlog_historia"
    id: "SERVICE-0604902B4FAD42B6"
    metrics:
      total_connections_count: "builtin:service.dbconnections.total"
      failure_rate: "builtin:service.dbconnections.failureRate"
      success_rate: "builtin:service.dbconnections.successRate"
      failed_connections_count: "builtin:service.dbconnections.failure"

polling:
  resolution: "1m"
  from_time: "now-15m"
  to_time: "now"
  
